import type { Metadata } from "next";
import { PublicShell } from "@/components/PublicShell";
import { ButtonLink } from "@/components/ui";

export const metadata: Metadata = { title: "Nosotros" };
const principles = [
  ["01", "Claridad operativa", "Una persona debe entender qué hacer, por qué y con qué información, sin depender de una explicación paralela."],
  ["02", "Trazabilidad útil", "Registramos decisiones y cambios para resolver problemas, no para añadir vigilancia o burocracia."],
  ["03", "Mejora desde la práctica", "Los procesos evolucionan con datos y conversaciones de quienes los ejecutan todos los días."],
];
export default function AboutPage() {
  return <PublicShell><main id="main-content">
    <section className="mx-auto grid w-[min(1180px,calc(100%-2.5rem))] grid-cols-[1.4fr_.6fr] items-end gap-[clamp(3rem,8vw,8rem)] py-[clamp(4rem,9vw,8rem)] max-[880px]:grid-cols-1 max-[880px]:items-start"><div><p className="text-xs font-extrabold uppercase tracking-[.1em] text-primary">Sobre Docli</p><h1 className="text-[clamp(3rem,6vw,5.8rem)] font-bold">El trabajo puede ser complejo.<br />Coordinarlo no debería serlo.</h1><p className="text-muted">Docli nació de un patrón que se repite en equipos muy distintos: el proceso existe, pero está repartido entre conversaciones, archivos y conocimiento informal. Cuando falta una persona, también falta el mapa para continuar.</p></div><blockquote className="m-0 border-l-2 border-[#83cac7] pl-6 font-semibold"><span className="mb-3 block text-xs uppercase text-muted">Lo que nos mueve</span>Convertir acuerdos de trabajo en procesos que cualquier equipo pueda ejecutar, revisar y mejorar.</blockquote></section>
    <section className="grid grid-cols-[70px_.7fr_1fr] gap-[clamp(1.5rem,5vw,5rem)] bg-[#153740] px-[max(1.25rem,calc((100vw-1180px)/2))] py-[clamp(4rem,8vw,7rem)] text-[#e7f1f2] max-[880px]:grid-cols-[45px_1fr] max-sm:grid-cols-1"><span className="max-sm:hidden">01</span><div><p className="text-xs font-extrabold uppercase tracking-[.1em] text-primary">Nuestro punto de partida</p><h2 className="text-3xl font-bold">Primero hacemos visible el trabajo.</h2></div><div className="max-[880px]:col-start-2 max-sm:col-auto"><p className="text-[#b8ced1]">Vimos equipos perder horas preguntando por avances, reconstruyendo decisiones y buscando la versión correcta de un documento. No era falta de compromiso: faltaba una forma compartida de operar.</p><p className="text-[#b8ced1]">Por eso unimos pasos, responsables, fechas, archivos y estados. Docli no obliga a trabajar igual a una firma legal, una operación de servicios o un equipo de salud; les da una estructura común que cada uno puede adaptar.</p><strong className="block border-t border-white/12 pt-6">Una buena herramienta no reemplaza el criterio del equipo: le da contexto para actuar.</strong></div></section>
    <section className="bg-white px-[max(1.25rem,calc((100vw-1180px)/2))] py-[clamp(4rem,8vw,7rem)]"><div className="mx-auto mb-10 max-w-180 text-center"><span className="text-xs font-extrabold uppercase tracking-[.1em] text-primary">Cómo construimos</span><h2 className="my-2 text-[clamp(2.2rem,4vw,3.4rem)] font-bold">Principios que se notan al trabajar.</h2></div><div className="grid grid-cols-3 border-t border-line max-[880px]:grid-cols-1">{principles.map((item) => <article className="border-r border-line p-8 last:border-r-0 max-[880px]:border-b max-[880px]:border-r-0" key={item[0]}><span className="font-extrabold text-primary">{item[0]}</span><h3 className="mt-3 text-xl font-bold">{item[1]}</h3><p className="text-muted">{item[2]}</p></article>)}</div></section>
    <section className="mx-auto grid w-[min(1180px,calc(100%-2.5rem))] grid-cols-2 gap-[clamp(3rem,8vw,8rem)] py-[clamp(4rem,9vw,8rem)] max-[880px]:grid-cols-1"><div><p className="text-xs font-extrabold uppercase tracking-[.1em] text-primary">Hacia dónde vamos</p><h2 className="text-3xl font-bold">Equipos autónomos, procesos que aprenden.</h2></div><div><p className="text-muted">Queremos que cualquier organización pueda pasar de “así lo hacemos” a un sistema operativo comprensible: suficientemente firme para sostener el estándar y suficientemente flexible para mejorar.</p><dl>{[["Diseñar","el flujo y sus criterios"],["Ejecutar","con contexto y responsables"],["Medir","tiempos, carga y resultados"]].map(([term, detail]) => <div className="grid grid-cols-[140px_1fr] border-b border-line py-4" key={term}><dt>{term}</dt><dd className="text-muted">{detail}</dd></div>)}</dl></div></section>
    <section className="mx-auto mb-24 flex w-[min(1180px,calc(100%-2.5rem))] items-end justify-between gap-8 rounded-[26px] bg-primary-soft p-12 max-[880px]:flex-col max-[880px]:items-start"><div><p className="text-xs font-extrabold uppercase tracking-[.1em] text-primary">Conoce el producto</p><h2 className="text-3xl font-bold">Prueba Docli con un proceso que hoy dependa de memoria.</h2></div><div className="flex gap-2 max-sm:w-full max-sm:flex-col"><ButtonLink className="max-sm:w-full" href="/login">Entrar a Docli →</ButtonLink><ButtonLink className="max-sm:w-full" href="/planes" secondary>Ver planes</ButtonLink></div></section>
  </main></PublicShell>;
}
